### ISSUE TITLE
Close To Home

### ISSUE THREAD

**Issue by cmking54** [COSC-480-UCD-F16/guests-whole-class#10]
i noticed that you have done a lot of work with those that are disabled, and first I wanted to applaud that. My little brother is a low-functioning autistic. He doesn't speak much, but he loves playing with technology. It's really the only thing he consistently communicates with. So, to cut the chase, have you ever thought of developing some system of expression for those have almost no typical means of doing so? if not, can you reference any work of your's that seems to be on the same path?

**Comment by pcho95** [comment]
Great question Chris! I've worked with children before who also have difficult expressing thought/emotion the way that society typically understands, so this is of great interest to me too.
