### ISSUE TITLE
Fitness Tech/Interaction For Disabled Users

### ISSUE THREAD

**Issue by pcho95** [COSC-480-UCD-F16/guests-whole-class#25]
Given your experience with technology & methods meant for helping people become/stay fit and healthy together, do you have any findings on how special-case users interact with this technology differently? By special-case, I mean users that don't fit the primary target group of your studies -- perhaps users with physical or mental disabilities.

**Comment by pcho95** [comment]
Great questions, Paul!

**Comment by cmking54** [comment]
I mean, like I guess it is.
